from app.database.database import SessionLocal
from app.models.opportunity import Opportunity

def seed():
    db = SessionLocal()
    try:
        if db.query(Opportunity).count() > 0:
            return

        records = [
            Opportunity(
                kind="scholarship",
                title="AICTE - Pragati Scholarship Scheme For Girl Students (Technical Degree)",
                organization="All India Council for Technical Education (AICTE)",
                organization_type="Government",
                country="India",
                field="Technical Degree",
                description="Scholarship scheme listed on the National Scholarship Portal for eligible students.",
                required_degree="Technical Degree",
                minimum_cgpa=None,
                income_limit=None,
                amount_or_stipend="See official scheme specifications",
                deadline="2026-10-31",
                eligibility="See official scheme eligibility and specifications on NSP.",
                documents="See official NSP requirements.",
                official_url="https://scholarships.gov.in/All-Scholarships",
                source="National Scholarship Portal",
                verified=True,
            ),
            Opportunity(
                kind="scholarship",
                title="AICTE - Swanath Scholarship Scheme (Technical Degree)",
                organization="All India Council for Technical Education (AICTE)",
                organization_type="Government",
                country="India",
                field="Technical Degree",
                description="Scholarship scheme listed on the National Scholarship Portal for eligible technical-degree students.",
                required_degree="Technical Degree",
                amount_or_stipend="See official scheme specifications",
                deadline="2026-10-31",
                eligibility="See official scheme eligibility and specifications on NSP.",
                documents="See official NSP requirements.",
                official_url="https://scholarships.gov.in/All-Scholarships",
                source="National Scholarship Portal",
                verified=True,
            ),
            Opportunity(
                kind="scholarship",
                title="PM-USP – Central Sector Scheme of Scholarship for College and University Students",
                organization="Department of Higher Education, Government of India",
                organization_type="Government",
                country="India",
                field="College and University",
                description="Central sector scholarship scheme listed on NSP for eligible college and university students.",
                required_degree="College or University",
                amount_or_stipend="See official scheme specifications",
                deadline="2026-10-31",
                eligibility="See official scheme eligibility and specifications on NSP.",
                documents="OTR and scheme-specific documents as stated by NSP.",
                official_url="https://scholarships.gov.in/All-Scholarships",
                source="National Scholarship Portal",
                verified=True,
            ),
            Opportunity(
                kind="scholarship",
                title="National Scholarship for Post Graduate Studies",
                organization="University Grants Commission (UGC)",
                organization_type="Government",
                country="India",
                field="Post Graduate",
                description="UGC scholarship scheme listed on the National Scholarship Portal.",
                required_degree="Post Graduate",
                amount_or_stipend="See official scheme specifications",
                deadline="2026-10-31",
                eligibility="See official scheme eligibility and specifications on NSP.",
                documents="See official NSP requirements.",
                official_url="https://scholarships.gov.in/All-Scholarships",
                source="National Scholarship Portal",
                verified=True,
            ),
            Opportunity(
                kind="internship",
                title="Chrome Extensions Developer Internship",
                organization="PITECHPEDIA OPC PRIVATE LIMITED",
                organization_type="Private",
                country="India",
                state="Pan India",
                location="Remote",
                remote=True,
                field="Web Development",
                description="Virtual internship focused on Chrome extensions, HTML, CSS, JavaScript, Manifest V3 and browser APIs.",
                required_degree="Any",
                required_skills="HTML, CSS, JavaScript, Web Development",
                amount_or_stipend="₹0 /month",
                duration="2 months",
                deadline="2026-09-20",
                eligibility="Students interested in browser extension development and web technologies.",
                documents="See official application page.",
                official_url="https://internship.aicte-india.org/",
                source="AICTE National Internship Portal",
                verified=True,
            ),
            Opportunity(
                kind="internship",
                title="Lead Generation",
                organization="Resolute AI Software Private Limited",
                organization_type="Private",
                country="India",
                state="Pan India",
                location="Work From Home",
                remote=True,
                field="Business / Sales",
                description="Work-from-home internship involving research, prospecting, LinkedIn outreach and sales coordination.",
                required_degree="Any",
                required_skills="Email Marketing, English, Lead Generation, LinkedIn Marketing, MS Excel, MS Office",
                amount_or_stipend="₹5000 /month",
                duration="6 months",
                deadline="2026-10-30",
                eligibility="Any specialization; relevant skills and interests; six-month availability.",
                documents="See official application page.",
                official_url="https://internship.aicte-india.org/",
                source="AICTE National Internship Portal",
                verified=True,
            ),
            Opportunity(
                kind="internship",
                title="Naval Architecture & Ocean Engineering Intern",
                organization="EduRankAI",
                organization_type="Private",
                country="India",
                state="Pan India",
                location="Pan India",
                remote=False,
                field="Engineering",
                description="Internship listing published on the AICTE National Internship Portal.",
                required_degree="Engineering",
                amount_or_stipend="Unpaid internship",
                duration="3 months",
                deadline="2026-12-31",
                eligibility="See official listing for current requirements.",
                documents="See official application page.",
                official_url="https://internship.aicte-india.org/",
                source="AICTE National Internship Portal",
                verified=True,
            ),
        ]
        db.add_all(records)
        db.commit()
    finally:
        db.close()
